### ISSUE TITLE
No SPOT tokens after payment

### ISSUE THREAD

**Issue by kap2fox** [airalab/spot-sdk.education#12]
In the section 2 with payment details I did a transaction associated with 5GWzem4MM5eFnxHKPS2eBTHQUaaj3dBGtrbGKe36QVn4xFLq Kusama address. There is no SPOT tokens after.

**Comment by vol4tim** [comment]
Hi

Address 5GWzem4MM5eFnxHKPS2eBTHQUaaj3dBGtrbGKe36QVn4xFLq on the statemine network is H2cK5QDySfBYc6mA8qh5QeQdArxrHzTMES1iJK3tHzZh84B
and tokens came to it.

You can check either on portal https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-statemine-rpc.paritytech.net#/assets/balances
or in explorer https://statemine.statescan.io/account/H2cK5QDySfBYc6mA8qh5QeQdArxrHzTMES1iJK3tHzZh84B?tab=assets
